apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxuin3625-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxuin3625-tenant-component
    app.kubernetes.io/part-of: loadxuin3625-tenant-app
  name: loadxuin3625-tenant-component
  namespace: loadxuin3625-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadxuin3625-tenant-component
    weight: null
status: {}
